pipeline {
    agent any
    tools {
        maven 'Maven'
        jdk 'JDK21'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/lenam0910/Stratec.git', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                withMaven(maven: 'Maven') {
                    sh 'mvn clean package'
                }
            }
        }
        stage('Test') {
            steps {
                withMaven(maven: 'Maven') {
                    sh 'mvn test'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t satrect-app:latest .'
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                if [ -n "$(docker ps -q --filter name=satrect-app)" ]; then
                    docker stop satrect-app
                fi
                if [ -n "$(docker ps -a -q --filter name=satrect-app)" ]; then
                    docker rm satrect-app
                fi
                docker run -d --name satrect-app -p 8081:8080 satrect-app:latest
                '''
            }
        }
    }
    post {
        always {
            echo 'Pipeline completed!'
        }
        success {
            echo 'Build and deployment successful!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}