# Cấu hình kết nối PostgreSQL
server:
    port: 8888

spring:
    datasource:
        url: jdbc:postgresql:18.183.3.126/:5432/satrect
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  SECRET_KEY: ZklN7dQKtUB/eJHNKevcGXKr9GEh/CYGec9i0ZfkmQFeWUD0npk60wxnhMjS9xxu

gemini:
  api:
    key: AIzaSyAGvATwDdavDTN-7fk6lsv2mZroP94cJaM
    url: https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent



minio:
    url: http://18.183.3.126/:9000
    access-key: minio
    secret-key: minio123
    bucket: image-stratec