# Cấu hình kết nối PostgreSQL
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/stratec
        username: postgres
        password: 123456
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  SECRET_KEY: ZklN7dQKtUB/eJHNKevcGXKr9GEh/CYGec9i0ZfkmQFeWUD0npk60wxnhMjS9xxu